### ISSUE TITLE
Text field not changed

### ISSUE THREAD

**Issue by atoo** [fpt-software/Material-Controls-for-Sencha-Touch#5]
Hi,
I'm trying to use the text field from the package, but the sencha default textfield is still rendered. I have included
requires: [
         'Material.components.field.Text'
    ],
then instantiate the item with xtype:'textfield'.
In app.scss, i added
@import '../../packages/Material/sass/src/Material.scss';
@include md-ripple;
@include md-button;
@include md-text-field;
Thanks

**Comment by trunghq307** [comment]
Hi,
You must to config  for textfield component : labelAlign: 'top'
Example:
                         {
                            xtype: 'textfield',
                            label: 'Username',
                            labelAlign: 'top',
                            width: '700px'
                         }
I hope that help you.

**Comment by atoo** [comment]
Thanks it works!
